# ESTIMA LOS DIAS AL CIERRE

dcv <- mutate(CV, DIA_VEN_EST=DIAS_VENCIDOS+ds)

# COLOCAR LOS NOMBRES DE LOS TITULOS 

tod00 <- rename(tod0, "BANCO"="V1","IBS"="V2","PRIMER_NOMBRE"="V3","SEGUNDO_NOMBRE"="V4","PRIMER_APELLIDO"="V5","SEGUNDO_APELLIDO"="V6","NOMBRE_CLIENTE"="V7","TIPO_CLIENTE"="V8","RIF_CI"="V9","CODIGO_AGENCIA"="V10","NOMBRE_AGENCIA"="V11","CODIGO_EJECUTIVO"="V12","NOMBRE_EJECUTIVO"="V13","TIPO_BANCA"="V14","ZONA_AREA"="V15","IBS_GRUPO_ECONOMICO"="V16","GRUPO_ECONOMICO"="V17","MONTO_ACTIVO_GRUPO_ECONOMICO"="V18","PRESTAMO"="V19","PROPUESTA"="V20","MONTO_ORIGINAL"="V21","SALDO_ACTUAL"="V22","MONTO_VIGENTE"="V23","MONTO_REESTRUCTURADO"="V24","MONTO_VENCIDO"="V25","MONTO_LITIGIO"="V26","MONTO_INMOVILIZADO"="V27","DIAS_VENCIDOS"="V28","CANTIDAD_CUOTAS_VENCIDAS_COMERCIAL"="V29","ESTATUS_COMERCIAL_CREDITO"="V30",	"CANTIDAD_PRORROGAS"="V31","FECHA_ULTIMA_PRORROGA"="V32","CLASIFICACION_RIESGO"="V33","PCT_PROVISION"="V34","MONTO_PROVISION_ESPECIFICA"="V35","MONTO_PROVISION_ESPECIFICA_INTERESES"="V36","CUENTA_CONTABLE"="V37","DESCRIPCION_CUENTA_CONTABLE"="V38","ESTATUS_CONTABLE"="V39","DESCRIPCION_ESTATUS_CONTABLE"="V40","TIPO_PRODUCTO"="V41","PRODUCTO_DESCRIPCION"="V42","SUB_PRODUCTO"="V43","SUB_PRODUCTO_DESCRIPCION"="V44","FECHA_LIQUIDACION"="V45","FECHA_VENCIMIENTO_ACTUAL"="V46","FECHA_VENCIMIENTO_ORIGINAL"="V47","PERIODICIDAD"="V48","PERIODICIDAD_CANT"="V49","FECHA_CANCELACION_ULTIMA_CUOTA"="V50","FECHA_CANCELACION_ULTIMA_CUOTA_CAPITAL"="V51","FECHA_VENCIMIENTO_PROX_CUOTA"="V52","MONTO_PROX_CUOTA"="V53","CUOTA_PRINCIPAL"="V54","CUOTA_INTERESES"="V55","OTROS_CARGOS"="V56","CICLO_CAPITAL"="V57","FECHA_DE_CUOTA_PRINCIPAL"="V58","CICLO_INTERESES"="V59","FECHA_CUOTA_INTERESES"="V60","TASA_INTERES"="V61","TIPO_CALCULO_INTERESES"="V62","SALDO_INTERES"="V63","RENDIMIENTOS_COBRAR_VIGENTES"="V64","RENDIMIENTOS_COBRAR_VENCIDOS"="V65","INTERESES_COBRAR_CUENTA_ORDEN"="V66","INTERESES_COBRADOS_ANTICIPADOS"="V67","TIPO_GARANTIA"="V68","DESCRIPCION_GARANTIA"="V69","REFERENCIA_GARANTIA"="V70","MONTO_GARANTIA"="V71","MONEDA"="V72","LINEA_CREDITO"="V73","LINEA_CREDITO_UTILIZADA"="V74","LINEA_CREDITO_DISPONIBLE"="V75","TIPO_LINEA_CREDITO"="V76",
                "DESCRIPCION_TIPO_LINEA_CREDITO"="V77","FECHA_VENCIMIENTO_LINEA_CREDITO"="V78","CUENTA_DEBITO_REPAGO"="V79","TIPO_CUENTA_DEBITO_REPAGO"="V80","SALDO_DISPONIBLE"="V81","PROMEDIO_TRIMESTRAL_CUENTA"="V82","CODIGO_ACTIVIDAD_ECONOMICA"="V83","DESCRIPCION_ACTIVIDAD_ECONOMICA"="V84","SECTOR_ECONOMICO"="V85","CODIGO_DESTINO_FONDOS"="V86","DESCRIPCION_CODIGO_DESTINO_FONDOS"="V87","FECHA_CONSTITUCION_NACIMIENTO"="V88","FECHA_VIGENCIA_VENCIMIENTO"="V89","NUMERO_EMPLEADOS"="V90","FECHA_ULTIMO_EEFF_AUDITADO"="V91","MONTO_INGRESOS_VENTAS_ANUALES"="V92","MONTO_PATRIMONIO"="V93","MONTO_MAXIMO_RIESGO_ASUMIDO"="V94","REFERENCIA_CARTA_CREDITO"="V95","TIPO_MODULO"="V96","CIUDAD"="V97","ESTADO"="V98","CAPITAL_PAGADO"="V99","CODIGO_SEXO"="V100",	"SEXO_DESCRIPCION"="V101","ESTADO_CIVIL"="V102","ESTADO_CIVIL_DESCRIPCION"="V103","NACIONALIDAD"="V104","CARGAS_FAMILIARES"="V105","TIPO_VIVIENDA"="V106","ANTIGUEDAD_RESIDENCIA"="V107","LUGAR_NACIMIENTO"="V108","CODIGO_NIVEL_EDUCACION"="V109","DESCRIPCION_NIVEL_EDUCACION"="V110",
                "CODIGO_PROFESION"="V111","DESCRIPCION_PROFESION"="V112","FUENTE_INGRESOS"="V113","DESCRIPCION_FUENTE_INGRESOS"="V114","OCUPACION"="V115","DESCRIPCION_OCUPACION"="V116","ACCIONISTA"="V117","PCT_ACCIONARIO"="V118","ID_ACCIONISTA"="V119","ADMINISTRACION"="V120","CARGO"="V121","ID_ADMINISTRADOR"="V122","SOLVENCIA"="V123","LIQUIDEZ"="V124","CAPITAL_TRABAJO"="V125","DIAS_MANO_COBRANZA"="V126","DIAS_MANO_CUENTAS_PAGAR"="V127","DIAS_MANO_INVENTARIO"="V128","DIAS_CICLO_ECONOMICO"="V129","APALANCAMIENTO"="V130","VENTAS_PASIVO_CIRCULANTE"="V131","AUTONOMIA_FINANCIERA"="V132","EBITDA"="V133","DEUDA_BANCARIA_VENTAS"="V134","RENTABILIDAD_UTILIDAD_NETA_VTAS"="V135","ROE_UTILIDAD_NETA_PATRIMONIO"="V136","PASIVO_CIRCULANTE_VENTAS"="V137","PASIVO_TOTAL_VENTAS"="V138","VARIACION_VENTAS"="V139","ESTRUCTURA_COSTOS_GASTOS"="V140","ACTIVO_CIRCULANTE_TOTAL_ACTIVO"="V141","INMUEBLES_TOTAL_ACTIVO"="V142","INV_LIQUIDAS_TOTAL_ACTIVO"="V143","INGRESO_ANUAL_PASIVO_CIRCULANTE"="V144","INGRESO_ANUAL_SERVICIO_DEUDA"="V145",
                "TOTAL_PASIVO_TOTAL_ACTIVO"="V146","INMUEBLES_TOTAL_PASIVO"="V147","FECHA_VENCIMIENTO_DOCUMENTO_PAGARE"="V148","FECHA_VENCIMIENTO_ACTUAL_PAGARE"="V149","NUMERO_PRORROGAS_PAGARE"="V150","CODIGO_SECTOR_ECONOMICO"="V151","VACIO"="V152"
)

# LIMPIAR LOS ESPACIOS EN BLANCOS

for (i in names(tod00)) {
  if(class(tod00[, i]) %in% c("factor", "character")){
    tod00[, i] <- trimws(tod00[, i])
  }
}

# SE AJUSTA LOS FORMATOS

options(scipen=999) #elimanar la notacion cientifica

tod00$SALDO_ACTUAL <- gsub("[.]","",tod00$SALDO_ACTUAL)
tod00$SALDO_ACTUAL <- gsub(",",".",tod00$SALDO_ACTUAL)
tod00$SALDO_ACTUAL <- as.numeric(tod00$SALDO_ACTUAL)

tod00$FECHA_LIQUIDACION <- as.Date(tod00$FECHA_LIQUIDACION, format="%d/%m/%y")
tod00$FECHA_VENCIMIENTO_ACTUAL <- as.Date(tod00$FECHA_VENCIMIENTO_ACTUAL, format="%d/%m/%y")
tod00$FECHA_VENCIMIENTO_ORIGINAL <- as.Date(tod00$FECHA_VENCIMIENTO_ORIGINAL, format="%d/%m/%y")

# CALCULAR LOS DIAS FUERA DE PLAZO TRAER EL DIA AL CIERRE 

tod00 <- mutate(tod00, CIERRE)
tod00$CIERRE <- as.Date(tod00$CIERRE)

# LLEVAR TODO A LA MISMA PERIODICIDAD Y CALCULAR LOS DIAS FUERA DE PLAZO

tod01 <- mutate(tod00, DIAS = ifelse (tod00$PERIODICIDAD=="Y", 360, ifelse (tod00$PERIODICIDAD=="M", 30, ifelse (tod00$PERIODICIDAD=="D",1,0))),DFP=30, SUB_CNT=substring(tod00$CUENTA_CONTABLE, 4, 5), TOT_DIAS = PERIODICIDAD_CANT * DIAS, FECHA_EST = FECHA_LIQUIDACION+TOT_DIAS+DFP, DIAS_FP = CIERRE-FECHA_EST) 

# CAMBIAR EL FORMATO DE LA FECHA ESTIMADA

tod01$DIAS_FP <- as.numeric(tod01$DIAS_FP)

# SE CONDIRA DESGLOSA LA CUENTA CONTABLE

tod01 <- filter(tod01, SUB_CNT == 35 | SUB_CNT == 37 | SUB_CNT == 47 | SUB_CNT == 57 | SUB_CNT == 05)
                
# SELECCIONA LAS VARIABLES

dcv1 <- select(dcv, PRESTAMO, DIA_VEN_EST)

# UNIR LOS DIAS ESTIMADOS

tod02 <- left_join(tod01, dcv1, by="PRESTAMO")

# SE AJUSTA LOS DIAS QUE TIENEN CERO EN FUERA DE PLAZO 

tod02$DIA_VEN_EST <- ifelse(is.na(tod02$DIA_VEN_EST),0,tod02$DIA_VEN_EST)
